### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribute 'shape'

### ISSUE THREAD

**Issue by roseyunzi** [CVI-SZU/CCAM#2]
Sorry to bother you again.When i use train_CCAM.py in CUSTOM to train a model using custom data, a got an EEOR:

`/data/yunzi/CCAM/CUSTOM$ OMP_NUM_THREADS=16 CUDA_VISIBLE_DEVICES=5 python train_CCAM.py --tag CCAM_Maket1501_MOCO --batch_size 1 --pretrained mocov2 --alpha 0.25
[i] CCAM_Maket1501_MOCO

[i] mean values is [0.485, 0.456, 0.406]
[i] std values is [0.229, 0.224, 0.225]
[i] train_transform is Compose(
    Resize(size=(256, 128), interpolation=bilinear, max_size=None, antialias=None)
    RandomHorizontalFlip(p=0.5)
    ToTensor()
    Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
)
[i] #train data

[i] log_iteration : 2,587
[i] val_iteration : 12,936
[i] max_iteration : 129,360
Loading unsupervised mocov2 pretrained parameters!
======================================================
[i] Architecture is resnet50
[i] Total Params: 23.54M

Traceback (most recent call last):
  File "train_CCAM.py", line 229, in <module>
    visualize_heatmap(args.tag, images.clone().detach(), ccam, 0, iteration)
  File "/data/yunzi/CCAM/CUSTOM/utils.py", line 49, in visualize_heatmap
    for j in range(axes.shape[0]):
AttributeError: 'AxesSubplot' object has no attribute 'shape'`

Do you have the same problem?

**Comment by roseyunzi** [comment]
I sloved it by replacing 'axes.shape[0]' with 'n' in utils.py line 49 and line 50.
